<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Enverif — Open-source revenue agents that actually operate</title><meta name="description" content="Enverif is an open-source, self-hosted AI revenue-agent operating system with agentic chat, visual workflows, Gmail/Outlook/SMTP automation, leads, schedules, skills, plugins and approval-first execution."><link rel="canonical" href="https://enverif.com/"><meta property="og:title" content="Enverif — The open-source agent operating system for revenue"><meta property="og:description" content="Research, qualify, automate and coordinate revenue work from one agentic workspace. Self-hosted, BYOK and MIT licensed."><meta property="og:type" content="website"><meta property="og:url" content="https://enverif.com/"><meta property="og:image" content="https://enverif.com/assets/social-preview.svg"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/enverif-mark.svg"><link rel="stylesheet" href="/assets/site.css"><script type="application/ld+json">{"@context":"https://schema.org","@type":"SoftwareApplication","name":"Enverif","applicationCategory":"BusinessApplication","operatingSystem":"Web","license":"https://opensource.org/license/mit","url":"https://github.com/ShubhamTuts/enverif","creator":{"@type":"Organization","name":"Codefreex"},"description":"Open-source self-hosted agent operating system for revenue."}</script></head><body>
<nav class="site-nav"><a class="site-brand" href="/"><img src="/assets/enverif-mark.svg" alt="Enverif"><span><strong>Enverif</strong></span></a><div class="site-links"><a href="#product">Product</a><a href="https://docs.enverif.com/overview">Docs</a><a href="#hosting">Self-host</a><a href="https://docs.enverif.com/contributing">Contribute</a><a class="site-nav-cta" href="https://github.com/ShubhamTuts/enverif" target="_blank" rel="noopener">Star on GitHub ↗</a></div></nav>
<main><section class="site-hero"><div class="site-kicker"><span></span> OPEN SOURCE · SELF-HOSTED · BYOK</div><h1>Your revenue team,<br><em>operating as agents.</em></h1><p>One ChatGPT-like workspace for research, prospecting, qualification, follow-up, schedules and durable workflows — with Gmail, Outlook, SMTP, plugins, skills and human approval exactly where external actions need it.</p><div class="site-actions"><a class="site-button primary" href="https://docs.enverif.com/installation">Install Enverif</a><a class="site-button" href="https://github.com/ShubhamTuts/enverif" target="_blank" rel="noopener">Explore source</a></div><div class="site-proof"><span>Laravel 13</span><span>Redis optional</span><span>Shared-host ready</span><span>MIT licensed</span><span>English · Français · Nederlands</span></div></section>
<section class="product-shell" aria-label="Enverif agentic chat preview"><aside><div class="mini-brand"><img src="/assets/enverif-mark.svg" alt=""><b>Enverif</b></div><button>＋ New chat</button><small>Workspace</small><a>Agents</a><a>Schedules</a><a>Leads</a><a>Campaigns</a><a>Skills</a><a>Plugins</a><a>Workflows</a><div class="mini-bottom"><a>Help & docs</a><a>Settings</a><span>● Operator</span></div></aside><div class="product-chat"><div class="preview-top"><span>Revenue workspace</span><span>Approval queue · 0</span></div><div class="preview-center"><img src="/assets/enverif-mark.svg" alt=""><h2>What should the revenue team do?</h2><p>Choose an agent, model and effort; add @plugins, @skills, @workflows or private files; then give Enverif the outcome.</p><div class="prompt-pills"><span>Research 50 qualified companies</span><span>Build a follow-up workflow</span><span>Review replies and update leads</span></div></div><div class="preview-composer"><div><b>@SDR Agent</b><b>@Apollo</b><b>@Gmail</b></div><p>Find high-intent prospects, enrich decision makers, draft personalized outreach and prepare each send for approval.</p><span>＋ Context · Attach files · Model · Effort <i>↗</i></span></div></div></section>
<section class="stack-strip"><span>PLUG INTO YOUR REVENUE STACK</span><div><b>G</b> Gmail <b>O</b> Outlook <b>SMTP</b> Mail <b>AP</b> Apify <b>AO</b> Apollo <b>GA</b> Analytics <b>GSC</b> Search Console <b>C</b> Calendly <b>MCP</b> MCP <b>↗</b> n8n · Zapier · Make</div></section>
<section class="site-section" id="product"><div class="site-heading"><span>FROM PROMPT TO OPERATION</span><h2>Not another chatbot. A durable operating layer for revenue work.</h2><p>Enverif keeps the conversational interface simple while execution remains persisted, permissioned, inspectable and resumable underneath.</p></div><div class="feature-cards"><article><b>01</b><h3>Agentic chat</h3><p>Searchable persistent threads remember agent, model and effort. Override per message, add private files and structured @context from the composer.</p></article><article><b>02</b><h3>Visual workflows</h3><p>Connect triggers, agents, connectors, conditions, delays, approvals, leads and campaigns, then validate with dry runs, retries and per-node inspection.</p></article><article><b>03</b><h3>Email automation</h3><p>Gmail OAuth, Microsoft Outlook OAuth and SMTP. Draft freely; external sends require approval by default.</p></article><article><b>04</b><h3>Durable agents</h3><p>MySQL-backed runs snapshot instructions, model, effort, skills, connector permissions and workflow definitions so edits never rewrite in-flight work.</p></article><article><b>05</b><h3>Revenue workspace</h3><p>Leads, provenance, activity history, campaigns, recurring schedules and reusable sales skills stay in one system.</p></article><article><b>06</b><h3>Open extension layer</h3><p>First-party plugins by Codefreex plus external connectors, SKILL.md playbooks and remote MCP servers.</p></article></div></section>
<section class="site-split" id="hosting"><div><span class="site-label">RUN IT ALMOST ANYWHERE</span><h2>VPS speed when you have Redis.<br>Shared-host simplicity when you don’t.</h2><p>Enverif adapts to the capabilities of the server instead of making Redis and permanent queue workers mandatory.</p><ul><li><strong>Performance mode</strong> — Redis queue/cache and persistent workers.</li><li><strong>Shared mode</strong> — MySQL queue/cache and one bounded cron command.</li><li><strong>Compatibility mode</strong> — signed Web Cron for hosts without CLI cron.</li><li>Root domain, subdomain and subfolder installations.</li><li>Apache routing and sensitive-path protection included.</li></ul><a class="site-text-link" href="https://docs.enverif.com/shared-hosting">Shared-hosting guide →</a></div><div class="terminal-card"><div><i></i><i></i><i></i><span>System health</span></div><pre><strong>Runtime</strong>             Shared hosting ✓
<strong>Queue</strong>               Database ✓
<strong>Cache</strong>               Database ✓
<strong>Scheduler heartbeat</strong> 34 seconds ago ✓
<strong>Redis</strong>               Optional / unavailable
<strong>Storage</strong>             Writable ✓

php /home/account/enverif/artisan enverif:tick</pre></div></section>
<section class="site-split reverse"><div class="workflow-card"><div class="wf-node trigger"><small>TRIGGER</small><b>New lead</b></div><span>→</span><div class="wf-node"><small>AGENT</small><b>Research & score</b></div><span>→</span><div class="wf-node"><small>CONDITION</small><b>Fit ≥ 80?</b></div><span>→</span><div class="wf-node approval"><small>APPROVAL</small><b>Send email</b></div></div><div><span class="site-label">CONTROLLED AUTONOMY</span><h2>Let agents work. Keep irreversible actions deliberate.</h2><p>Read, research, enrichment and internal organization can stay autonomous. Email sends and other external writes ask by default. Secrets always ask. Destructive actions never become silent.</p><a class="site-text-link" href="https://docs.enverif.com/security">Read the safety model →</a></div></section>
<section class="site-open"><div><span class="site-label">BUILT IN THE OPEN</span><h2>Extend Enverif instead of waiting for a roadmap.</h2><p>Contribute to the core, publish a connector, create a sales skill, improve translations or harden the docs. The first-party integration layer is maintained by Codefreex; third-party extensions retain their own attribution.</p><div class="site-actions left"><a class="site-button primary" href="https://docs.enverif.com/contributing">Contributor guide</a><a class="site-button" href="https://docs.enverif.com/core">Developer docs</a></div></div><div class="code-card"><div><i></i><i></i><i></i><span>enverif.plugin/v1</span></div><pre>{
  "name": "Your CRM",
  "developer": "Your team",
  "type": "connector",
  "capabilities": [
    "read",
    "network",
    "external_write"
  ]
}</pre></div></section>
<section class="site-cta"><img src="/assets/enverif-mark.svg" alt=""><h2>Build an AI revenue team you can inspect, control and own.</h2><p>Start with one agent. Add your models and email. Then turn repeatable revenue work into durable workflows.</p><div class="site-actions"><a class="site-button primary" href="https://docs.enverif.com/installation">Deploy Enverif</a><a class="site-button" href="https://github.com/ShubhamTuts/enverif" target="_blank" rel="noopener">GitHub ↗</a></div></section></main>
<footer class="site-footer"><a class="site-brand" href="/"><img src="/assets/enverif-mark.svg" alt=""><span><strong>Enverif</strong></span></a><p>The open-source agent operating system for revenue.</p><div><a href="https://docs.enverif.com/overview">Documentation</a><a href="https://docs.enverif.com/contributing">Contribute</a><a href="https://github.com/ShubhamTuts/enverif">GitHub</a><span>MIT © 2026 Codefreex and Enverif Contributors</span></div></footer></body></html>