<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {public function up():void{
 Schema::create('model_connections',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('provider',30);$t->string('name');$t->longText('credentials');$t->string('default_model')->nullable();$t->string('base_url')->nullable();$t->json('pricing')->nullable();$t->boolean('enabled')->default(true);$t->timestamp('last_tested_at')->nullable();$t->string('last_test_status',20)->nullable();$t->timestamps();$t->index(['workspace_id','provider']);});
 Schema::create('connector_connections',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('driver',40);$t->string('name');$t->longText('credentials')->nullable();$t->json('configuration')->nullable();$t->boolean('enabled')->default(true);$t->timestamp('last_tested_at')->nullable();$t->string('last_test_status',20)->nullable();$t->timestamps();$t->index(['workspace_id','driver']);});
 Schema::create('skills',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->nullable()->constrained()->cascadeOnDelete();$t->string('name');$t->string('slug');$t->text('description')->nullable();$t->string('version',30)->default('1.0.0');$t->string('source_type',20)->default('local');$t->text('source_url')->nullable();$t->string('source_ref')->nullable();$t->string('checksum',64)->nullable();$t->string('license',40)->nullable();$t->json('capabilities')->nullable();$t->longText('body');$t->string('status',20)->default('active');$t->boolean('built_in')->default(false);$t->timestamps();$t->unique(['workspace_id','slug']);});
 Schema::create('agent_skill',function(Blueprint $t){$t->foreignId('agent_id')->constrained()->cascadeOnDelete();$t->foreignId('skill_id')->constrained()->cascadeOnDelete();$t->timestamps();$t->primary(['agent_id','skill_id']);});
 Schema::create('agent_connector',function(Blueprint $t){$t->foreignId('agent_id')->constrained()->cascadeOnDelete();$t->foreignId('connector_connection_id')->constrained()->cascadeOnDelete();$t->json('allowed_actions')->nullable();$t->timestamps();$t->primary(['agent_id','connector_connection_id']);});
 Schema::create('mcp_servers',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('transport',20)->default('http');$t->text('endpoint');$t->longText('credentials')->nullable();$t->json('configuration')->nullable();$t->boolean('enabled')->default(true);$t->timestamps();});
 }public function down():void{Schema::dropIfExists('mcp_servers');Schema::dropIfExists('agent_connector');Schema::dropIfExists('agent_skill');Schema::dropIfExists('skills');Schema::dropIfExists('connector_connections');Schema::dropIfExists('model_connections');}};
