<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {public function up():void{
 Schema::create('leads',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('first_name')->nullable();$t->string('last_name')->nullable();$t->string('email')->nullable()->index();$t->string('phone')->nullable();$t->string('title')->nullable();$t->string('company')->nullable()->index();$t->text('website')->nullable();$t->text('linkedin_url')->nullable();$t->string('city')->nullable();$t->string('country')->nullable();$t->string('status',24)->default('new')->index();$t->unsignedTinyInteger('score')->default(0)->index();$t->string('source',50)->nullable();$t->text('source_url')->nullable();$t->longText('research_summary')->nullable();$t->json('data')->nullable();$t->timestamp('last_contacted_at')->nullable();$t->timestamps();$t->index(['workspace_id','created_at']);});
 Schema::create('lead_activities',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('lead_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->uuid('run_id')->nullable();$t->string('type',30);$t->text('summary');$t->json('data')->nullable();$t->timestamp('occurred_at')->useCurrent();$t->timestamps();});
 Schema::create('campaigns',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name');$t->text('description')->nullable();$t->string('status',20)->default('draft');$t->json('settings')->nullable();$t->timestamps();});
 Schema::create('campaign_steps',function(Blueprint $t){$t->id();$t->foreignId('campaign_id')->constrained()->cascadeOnDelete();$t->unsignedSmallInteger('position');$t->string('channel',30);$t->string('action',50);$t->unsignedInteger('delay_minutes')->default(0);$t->json('content')->nullable();$t->boolean('requires_approval')->default(true);$t->timestamps();$t->unique(['campaign_id','position']);});
 Schema::create('campaign_members',function(Blueprint $t){$t->foreignId('campaign_id')->constrained()->cascadeOnDelete();$t->foreignId('lead_id')->constrained()->cascadeOnDelete();$t->string('status',24)->default('queued');$t->unsignedSmallInteger('current_step')->default(0);$t->timestamp('next_action_at')->nullable();$t->timestamps();$t->primary(['campaign_id','lead_id']);});
 }public function down():void{Schema::dropIfExists('campaign_members');Schema::dropIfExists('campaign_steps');Schema::dropIfExists('campaigns');Schema::dropIfExists('lead_activities');Schema::dropIfExists('leads');}};
