<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {public function up():void{
 Schema::create('agents',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('slug');$t->text('description')->nullable();$t->longText('instructions');$t->string('status',20)->default('active');$t->foreignId('model_connection_id')->nullable();$t->string('model')->nullable();$t->unsignedSmallInteger('max_steps')->default(40);$t->unsignedInteger('max_runtime_seconds')->default(900);$t->decimal('max_cost_usd',10,4)->default(10);$t->json('policy')->nullable();$t->json('settings')->nullable();$t->timestamps();$t->unique(['workspace_id','slug']);});
 Schema::create('agent_runs',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('agent_id')->constrained()->cascadeOnDelete();$t->foreignUuid('parent_run_id')->nullable()->index();$t->string('status',24)->default('queued')->index();$t->text('input');$t->longText('output')->nullable();$t->string('stop_reason')->nullable();$t->unsignedSmallInteger('step_count')->default(0);$t->unsignedInteger('input_tokens')->default(0);$t->unsignedInteger('output_tokens')->default(0);$t->decimal('estimated_cost_usd',12,6)->default(0);$t->timestamp('started_at')->nullable();$t->timestamp('finished_at')->nullable();$t->timestamp('cancelled_at')->nullable();$t->json('context')->nullable();$t->timestamps();});
 Schema::create('agent_run_steps',function(Blueprint $t){$t->id();$t->uuid('run_id')->index();$t->unsignedSmallInteger('sequence');$t->string('type',32);$t->string('status',24)->default('pending');$t->string('tool')->nullable();$t->string('risk_level',24)->nullable();$t->json('input')->nullable();$t->longText('output')->nullable();$t->json('usage')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('finished_at')->nullable();$t->timestamps();$t->unique(['run_id','sequence']);$t->foreign('run_id')->references('id')->on('agent_runs')->cascadeOnDelete();});
 Schema::create('agent_messages',function(Blueprint $t){$t->id();$t->uuid('run_id')->index();$t->string('role',16);$t->longText('content');$t->json('meta')->nullable();$t->timestamps();$t->foreign('run_id')->references('id')->on('agent_runs')->cascadeOnDelete();});
 Schema::create('agent_artifacts',function(Blueprint $t){$t->id();$t->uuid('run_id')->index();$t->string('type',40);$t->string('name');$t->string('disk')->default('local');$t->string('path')->nullable();$t->json('data')->nullable();$t->timestamps();$t->foreign('run_id')->references('id')->on('agent_runs')->cascadeOnDelete();});
 }public function down():void{Schema::dropIfExists('agent_artifacts');Schema::dropIfExists('agent_messages');Schema::dropIfExists('agent_run_steps');Schema::dropIfExists('agent_runs');Schema::dropIfExists('agents');}};
