<?php
namespace App\Http\Controllers;
use App\Core\Scheduling\{CronExpressionLite,ScheduleTarget};use App\Models\{Agent,AgentSchedule,Workflow};use Cron\CronExpression;use Illuminate\Http\Request;use Illuminate\Validation\ValidationException;
final class ScheduleController {
 public function index(Request $request){$month=$request->string('month')->toString()?:now()->format('Y-m');try{$start=\Carbon\Carbon::createFromFormat('Y-m-d',$month.'-01')->startOfMonth();}catch(\Throwable){$start=now()->startOfMonth();}$end=$start->copy()->endOfMonth();$all=AgentSchedule::with(['agent','workflow'])->orderBy('next_run_at')->get();$calendar=$this->calendar($start,$all);return view('schedules.index',['schedules'=>AgentSchedule::with(['agent','workflow'])->latest()->paginate(20),'calendar'=>$calendar,'month'=>$start,'prevMonth'=>$start->copy()->subMonth()->format('Y-m'),'nextMonth'=>$start->copy()->addMonth()->format('Y-m')]);}
 public function show(AgentSchedule $schedule){$schedule->load(['agent','workflow']);return view('schedules.show',['schedule'=>$schedule]);}
 public function create(){return view('schedules.form',$this->formData(new AgentSchedule));}
 public function store(Request $request){$schedule=AgentSchedule::create($this->withNext($this->data($request)));return redirect()->route('schedules.show',$schedule)->with('status',__('ui.saved'));}
 public function edit(AgentSchedule $schedule){return view('schedules.form',$this->formData($schedule));}
 public function update(Request $request,AgentSchedule $schedule){$schedule->update($this->withNext($this->data($request)));return redirect()->route('schedules.show',$schedule)->with('status',__('ui.saved'));}
 public function destroy(AgentSchedule $schedule){$schedule->delete();return redirect()->route('schedules.index')->with('status',__('ui.deleted'));}
 public function toggle(AgentSchedule $schedule){$schedule->update(['enabled'=>!$schedule->enabled]);return back()->with('status',__('ui.saved'));}
 private function data(Request $request):array{$data=$request->validate(['target_type'=>'required|in:agent,workflow','agent_id'=>'nullable|integer','workflow_id'=>'nullable|integer','name'=>'required|max:120','cron_expression'=>'required|max:100','timezone'=>'required|max:64','prompt'=>'required|string|max:20000','enabled'=>'nullable|boolean']);if($data['target_type']==='agent'){$data['workflow_id']=null;if(!Agent::whereKey((int)($data['agent_id']??0))->where('status','active')->exists())throw ValidationException::withMessages(['agent_id'=>__('ui.agent_unavailable')]);}else{$data['agent_id']=null;if(!Workflow::whereKey((int)($data['workflow_id']??0))->where('status','active')->exists())throw ValidationException::withMessages(['workflow_id'=>'The selected workflow must be active.']);}ScheduleTarget::type($data['agent_id']??null,$data['workflow_id']??null);try{CronExpressionLite::fromString($data['cron_expression']);}catch(\InvalidArgumentException){throw ValidationException::withMessages(['cron_expression'=>__('ui.invalid_cron')]);}if(!CronExpression::isValidExpression($data['cron_expression']))throw ValidationException::withMessages(['cron_expression'=>__('ui.invalid_cron')]);if(!in_array($data['timezone'],timezone_identifiers_list(),true))throw ValidationException::withMessages(['timezone'=>__('ui.invalid_timezone')]);$data['enabled']=$request->boolean('enabled');unset($data['target_type']);return $data;}
 private function withNext(array $data):array{$data['next_run_at']=(new CronExpression($data['cron_expression']))->getNextRunDate('now',0,false,$data['timezone']);return $data;}
 private function formData(AgentSchedule $schedule):array{return ['schedule'=>$schedule,'agents'=>Agent::where('status','active')->orderBy('name')->get(),'workflows'=>Workflow::where('status','active')->orderBy('name')->get()];}
 private function calendar(\Carbon\Carbon $month,$schedules):array{$start=$month->copy()->startOfMonth()->startOfWeek(\Carbon\Carbon::MONDAY);$days=[];for($i=0;$i<42;$i++){$day=$start->copy()->addDays($i);$events=$schedules->filter(fn($s)=>$s->next_run_at&&$s->next_run_at->timezone($s->timezone)->isSameDay($day))->values();$days[]=['date'=>$day,'inMonth'=>$day->month===$month->month,'events'=>$events];}return $days;}
}
